# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "v2"

  config.vm.box_url = "https://dl.dropboxusercontent.com/s/haqiv201gqbkl2f/Ubuntu_13_10.box?dl=1&token_hash=AAFvxg-WeVwUCgd-gbJrTa7U_CBBDxXJrvWOQtgZzdVJnw"

  config.vm.network :private_network, ip: "192.168.33.2"
  config.vm.provision :shell, :path => "bootstrap.sh"

end
