# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/xenial64"
  
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/ubuntu/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      sudo apt-get update
      sudo apt-get -y install python
    SHELL
  end
  
  config.vm.define :db do |db|
    db.vm.network :private_network, ip: "192.168.66.4"
  end

  config.vm.define :backend do |backend|
    backend.vm.network :private_network, ip: "192.168.66.5"
  end

  config.vm.define :web do |web|
    web.vm.network :private_network, ip: "192.168.66.3"
  end

end
