#!/bin/sh

USER="cyc-engine" 
ROOT_DIR="/usr/local/cyc-engine-container/"
SERVER="engine-container-jar-with-dependencies.jar"
LOG_FILE="/var/log/cyc-engine.log"
 
do_start()
{
        if ps -efH | grep -i java.*$SERVER | grep -v "grep" -q ; then
                echo "$SERVER is locked."        
                RETVAL=1
        fi                        

        if [ -z "$RETVAL" ] ; then
                echo -n "Starting $SERVER: "
                cd $ROOT_DIR
                echo sudo -b -u $USER $ROOT_DIR/run.sh
                sudo -b -u $USER $ROOT_DIR/run-service.sh >> $LOG_FILE
                RETVAL=$?
                echo                
        fi

}
do_stop()
{
        echo -n "Shutdown $SERVER: "
        echo "exit" | nc localhost 9998        
        if [ $? != 0 ]; then        
                echo -n "Killing $SERVER: "
                pid=`ps -aefw | grep "$SERVER" | grep -v " grep " | awk '{print $2}'`
                kill -9 $pid > /dev/null 2>&1
                RETVAL=$?        
                [ $RETVAL -eq 0 ]
        else 
                while ps -efH | grep -i java.*$SERVER | grep -v "grep" -q ; do
                        sleep 1
                done
        fi

        echo
}
 
case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop                
                RETVAL=
                do_start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac
 
exit $RETVAL
