# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "v2"
  config.vm.box_url = "https://dl.dropboxusercontent.com/s/haqiv201gqbkl2f/Ubuntu_13_10.box?dl=1&token_hash=AAFvxg-WeVwUCgd-gbJrTa7U_CBBDxXJrvWOQtgZzdVJnw"
  
  config.vm.define :db do |db|
    db.vm.network :private_network, ip: "192.168.66.4"
  end

  config.vm.define :backend do |backend|
    backend.vm.network :private_network, ip: "192.168.66.5"
  end

  config.vm.define :web do |web|
    web.vm.network :private_network, ip: "192.168.66.3"
  end

end
